### ISSUE TITLE
環境設定について

### ISSUE THREAD

**Issue by yokookentarou** [IshitaTakeshi/RoadDamageDetector#2]
初めまして、記事を読み興味を持ちました。

環境設定で

依存パッケージのダウンロードやデータのダウンロード・展開はすべて自動で行なわれます。
git clone https://github.com/PasonaTech-Inc/anomaly_detection.git
cd anomaly_detection
./setting-environment.sh

という項目があると思うのですが、ダウンロード・展開ができないため、質問させていただきました。
どのように開けばよろしいか教えていただけると幸いです。

もう一つ質問なのですが、
コマンドにおいてpython3で通しているということでしょうか？
python3で行うとバッチ、またはファイルとして認識されなかったため質問させていただきました。

以上の二点が質問内容です
よろしくお願いします。

**Comment by IshitaTakeshi** [comment]
報告ありがとうございます

修正しました

**Comment by IshitaTakeshi** [comment]
開発は全てPython3で行っています
