### ISSUE TITLE
 I have a problem abot_load_npz in ssd_ressnet101.py

### ISSUE THREAD

**Issue by 760730895** [IshitaTakeshi/RoadDamageDetector#3]
Could you tell me about _load_npz in ssd_ressnet101.py ?
Because i can`t find _load_npz in chainercv.links.model.ssd.ssd_vgg16,
I found _imagenet_mean in the chainercv.links.model.ssd.ssd_vgg16(ssd_vgg16.py),
Could you tell me how _load_npz works and what it means ,Thanks so much ?

**Comment by IshitaTakeshi** [comment]
Thanks for the report. 
I just found that this doesn't work on chainercv of the latest version.
Could you try installing chainercv v0.9.0 and run the training script again?

```pip3 install chainercv==v0.9.0```

**Comment by 760730895** [comment]
okay , i will try it again ,thanks so much


 
---Original---
