### ISSUE TITLE
Your code is extremely nice!

### ISSUE THREAD

**Issue by ColdPiLLoW710** [IshitaTakeshi/RoadDamageDetector#5]
Hello from the internet! Your code is very nice and I want to contact you for further information and discussion.Looking forward to your earliest reply!

**Comment by IshitaTakeshi** [comment]
Could you write a light summary of your question?

**Comment by ColdPiLLoW710** [comment]
Perhaps something wrong with the accuracy. Does it have to with the training of yours? I am wondering if the training matters. Thx!
By the way, do u have some other social media so it will be more convenient for us to communicate.




------------------ Original ------------------
From: Takeshi Ishita ***@***.***&gt;
Date: Tue,Mar 15,2022 3:18 PM
To: IshitaTakeshi/RoadDamageDetector ***@***.***&gt;
Cc: ColdPiLLoW710 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [IshitaTakeshi/RoadDamageDetector] Your code is extremely nice!(Issue #5)

**Comment by ColdPiLLoW710** [comment]
![Uploading B7243FE0-A2BF-4BF1-B407-5F75EFE406FA.png…]()

**Comment by IshitaTakeshi** [comment]
I cannot see your photo

Accuracy of some labels is not good because of the insufficient number of images.
You can see the results in figure 3 (図3) and figure 5 (図5) in this article.

https://qiita.com/IshitaTakeshi/items/915de731d8081e711ae5

I hope to communicate here because other people can refer to our conversation when having similar questions.

**Comment by ColdPiLLoW710** [comment]
Something wrong with the link u give me，I can’t successfully log in.
My problem now is that could u tell me how train the model myself? In the wiki there is a link&nbsp;https://s3-ap-northeast-1.amazonaws.com/mycityreport/RoadDamageDataset.tar.gz&nbsp;that I can’t open.
Looking forward to ur earliest reply.



发自我的iPhone


------------------ Original ------------------
From: Takeshi Ishita ***@***.***&gt;
Date: Tue,Mar 15,2022 4:13 PM
To: IshitaTakeshi/RoadDamageDetector ***@***.***&gt;
Cc: ColdPiLLoW710 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [IshitaTakeshi/RoadDamageDetector] Your code is extremely nice! (Issue #5)





 
I cannot see your photo
 
Accuracy of some labels is not good because of the insufficient number of images.
 You can see the results in figure 3 (図3) and figure 5 (図5) in this article.
 
https://qiita.com/IshitaTakeshi/items/915de731d8081e711ae5
 
I hope to communicate here because other people can refer to our conversation when having similar questions.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IshitaTakeshi** [comment]
I can open the link https://qiita.com/IshitaTakeshi/items/915de731d8081e711ae5 in chrome's incognito mode. This doesn't require login

I fixed the dataset link. Thank you for your feedback.

**Comment by ColdPiLLoW710** [comment]
Hello from the Internet again! My question now is that how can I draw a figure like this to show it’s main/loss rate to iteration ?
Arigado!

发自我的iPhone


------------------ Original ------------------
From: Takeshi Ishita ***@***.***&gt;
Date: Tue,Mar 15,2022 6:28 PM
To: IshitaTakeshi/RoadDamageDetector ***@***.***&gt;
Cc: ColdPiLLoW710 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [IshitaTakeshi/RoadDamageDetector] Your code is extremely nice! (Issue #5)





 
Closed #5.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IshitaTakeshi** [comment]
In my understanding `vis_bbox` is already doing it

https://github.com/IshitaTakeshi/RoadDamageDetector/blob/master/demo.py#L43
