### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ColdPiLLoW710** [IshitaTakeshi/RoadDamageDetector#6]
Hello author. I would like to know if the images used for training in your program are taken by the car recorder? If not, what device was used?

**Comment by IshitaTakeshi** [comment]
I used a publicly-available dataset. You can find more information from here 

https://github.com/sekilab/RoadDamageDetector

**Comment by ColdPiLLoW710** [comment]
How long did you train this data? Adachi
&nbsp;for example&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Takeshi Ishita ***@***.***&gt;
Date: Wed,Mar 23,2022 2:28 PM
To: IshitaTakeshi/RoadDamageDetector ***@***.***&gt;
Cc: ColdPiLLoW710 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [IshitaTakeshi/RoadDamageDetector] A question (Issue #6)





 
I used a publicly-available dataset. You can find more information from here
 
https://github.com/sekilab/RoadDamageDetector

**Comment by IshitaTakeshi** [comment]
The time depends on the machine performance but the training curve is here

https://qiita.com/IshitaTakeshi/items/915de731d8081e711ae5#%E7%B5%90%E6%9E%9C

**Comment by ColdPiLLoW710** [comment]
hello，do u have F1-score of the training？



发自我的iPhone


------------------ Original ------------------
From: Takeshi Ishita ***@***.***&gt;
Date: Fri,Mar 25,2022 1:14 AM
To: IshitaTakeshi/RoadDamageDetector ***@***.***&gt;
Cc: ColdPiLLoW710 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [IshitaTakeshi/RoadDamageDetector] A question (Issue #6)





 
The time depends on the machine performance but the training curve is here
 
https://qiita.com/IshitaTakeshi/items/915de731d8081e711ae5#%E7%B5%90%E6%9E%9C

**Comment by IshitaTakeshi** [comment]
No, but there should be a lot of tools to calculate it so it will not be difficulut

**Comment by ColdPiLLoW710** [comment]
Thanks!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IshitaTakeshi/RoadDamageDetector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月23日(星期三) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IshitaTakeshi/RoadDamageDetector] A question (Issue #6)





 
I used a publicly-available dataset. You can find more information from here
 
https://github.com/sekilab/RoadDamageDetector
